inputs: ../atmosphere.pdf
outputs: outputs/ocr
visualize: True
tasks:
  ocr:
    model: ocr_ppocr
    model_config:
      lang: en
#      show_log: True
      det_model_dir: /storage/araia/models/OCR/paddleocr_torch/
      rec_model_dir: /storage/araia/models/OCR/paddleocr_torch/
      det_db_box_thresh: 0.3
