inputs: ../atmosphere.pdf
outputs: outputs/ocr
visualize: True
tasks:
  ocr:
    model: en_PP-OCRv5_rec_infer
    model_config:
      lang: ch
      show_log: True
      det_model_dir: /storage/PDF-Extract-Kit-sp/models/OCR/paddleocr_torch/
      rec_model_dir: /storage/PDF-Extract-Kit-sp/models/OCR/paddleocr_torch/
      det_db_box_thresh: 0.3
